### ISSUE TITLE
anvil_resources::<anvil_uuid>::ram::available returns negative number

### ISSUE THREAD

**Issue by Deezzir** [ClusterLabs/anvil#265]
`$anvil->data->{anvil_resources}{$anvil_uuid}{ram}{hardware}` reports 2.05GiB as expected, while `$anvil->data->{anvil_resources}{$anvil_uuid}{ram}{available}` reports -1.95GiB. Is the minus on purpose?
```
Provision a new server menu:
Anvil! name: ... [an-anvil-01]
Server name: ... [an-server]
CPU Cores: ..... [1]
RAM: ........... [-1.95 GiB]
? 

* Please enter a valid amount up to: [2.05 GiB / -1.95 GiB].

-=] Available RAM: [-1.95 GiB (-1,999.00 MiB)]
 - Reserved by host: ... [4.00 GiB]
 - Allocated to servers: [0 B (0.00 MiB)]
 - Node 1 RAM (total): . [2.05 GiB (2,097.00 MiB)]
 - Node 2 RAM (total): . [2.05 GiB (2,097.00 MiB)]
```
"Please enter a valid amount up to: ..." is produced by https://github.com/ClusterLabs/anvil/blob/6a8dd07f3642e2a2cc83840d0f5691bcbab002de/tools/anvil-provision-server#L2000-L2006

Related issues: #263 and #262

**Comment by Deezzir** [comment]
https://github.com/ClusterLabs/anvil/blob/7c0b0edc68039697b2957c94ab2ccc808571e65f/Anvil/Tools/Get.pm#L720-L723
Ah, here is why - the system expects the hardware RAM to be >= 4GiB. It takes 4GiB off the hardware RAM to determine available RAM - in case there is only 2GiB the result is -2GiB

**Comment by digimer** [comment]
Reserved RAM can now be configured, please see commit 89eae70.
