### ISSUE TITLE
[db] add files only after rsync is completed

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#271]
copy a huge iso file to /mnt/shared/incoming on striker01

once striker01 starts processing and move the file to shared/files:

[root@an-a01n02 ~]# anvil-provision-server --ci-test --options

already shows all the files available, while in reality they are still rsync´ing across all nodes.

**Comment by digimer** [comment]
I've been thinking about this, and I think I'm going to add a "file_ready" or similar DB variable that can be checked. Not adding to the DB until uploaded would require fairly significant reworking.

**Comment by digimer** [comment]
PR#328 includes the new 'file_location_ready' function, which includes anvil-provision-server holding before the virt-install call until the install (and driver) ISO files are "ready" on the local system before proceeding.

**Comment by digimer** [comment]
Resolved in PR#328. Re-open if the issue remains.
