### ISSUE TITLE
[tools] anvil-provision-server causes node02 to be powered off

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#273]
[root@an-a01n01 ~]# anvil-provision-server --ci-test --name an-test-deploy1 --os centos-stream9 --cpu 4 --ram 4G --storage-group ef10e3e9-18e3-4921-b2a8-35c6941da306 --storage-size 30G --install-media CentOS-Stream-9-latest-x86_64-dvd1.iso --driver-disc deploy1.iso

Saving the job details to create this server. Please wait a few moments.
Job Data:
====
server_name=an-test-deploy1
os=centos-stream9
cpu_cores=4
ram=4G
storage_group_uuid=ef10e3e9-18e3-4921-b2a8-35c6941da306
storage_size=30G
install_iso=6cb76bb0-d4c4-4fae-b52c-38b6ac9ef5b3
driver_iso=efa1ef14-3058-4f15-b546-a48a58b42917
====
The job to create the new server has been registered as job: [78cc6a8f-6362-422b-ac97-d191c1066d86].
It should be provisioned in the next minute or two.

from crm_mon -r:

Cluster Summary:
  * Stack: corosync
  * Current DC: an-a01n01 (version 2.1.5-4.el8-a3f44794f94) - partition with quorum
  * Last updated: Sat Dec 24 18:05:47 2022
  * Last change:  Sat Dec 24 16:17:51 2022 by root via cibadmin on an-a01n01
  * 2 nodes configured
  * 10 resource instances configured

Node List:
  * Online: [ an-a01n01 an-a01n02 ]

Full List of Resources:
  * ipmilan_node1       (stonith:fence_ipmilan):         Started an-a01n01
  * apc_snmp_node1_an-pdu01     (stonith:fence_apc_snmp):        Started an-a01n02
  * apc_snmp_node1_an-pdu02     (stonith:fence_apc_snmp):        Started an-a01n01
  * virt_node1_gravitar (stonith:fence_virt):    Started an-a01n02
  * delay_node1 (stonith:fence_delay):   Started an-a01n01
  * ipmilan_node2       (stonith:fence_ipmilan):         Started an-a01n02
  * apc_snmp_node2_an-pdu01     (stonith:fence_apc_snmp):        Started an-a01n01
  * apc_snmp_node2_an-pdu02     (stonith:fence_apc_snmp):        Started an-a01n02
  * virt_node2_gravitar (stonith:fence_virt):    Started an-a01n01
  * delay_node2 (stonith:fence_delay):   Started an-a01n02

Pending Fencing Actions:
  * turning off of an-a01n02 pending: client=stonith_admin.288262, origin=an-a01n01

node02 is powered off and never restarted.

**Comment by fabbione** [comment]
This happens also if the invocation is done from node02.

**Comment by fabbione** [comment]
it appears that something is invoking fence_pacemaker from node01. Found those logs:

messages:Dec 25 09:38:42 an-a01n01 fence_pacemaker[47567]: 115; DRBD pacemaker's stonith handler invoked.
messages:Dec 26 05:27:27 an-a01n01 fence_pacemaker[3408404]: 115; DRBD pacemaker's stonith handler invoked.

that corresponds on deploying server 1 and 2.

When deploying server 2, node02 was not poweroff, but pacemaker was stopped on the node, and never started again.

**Comment by fabbione** [comment]
The poweroff vs pacemaker stopped is due to another issue in fencing config. I will report that separately.

**Comment by digimer** [comment]
This should be resolved now.

**Comment by fabbione** [comment]
verified with latest main, deploy is working ok
