### ISSUE TITLE
[drbd] does not sync on node02 after node shutdown

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#274]
related to: https://github.com/ClusterLabs/anvil/issues/273

poweron node02, possible race condition, drbd does not connect.

[root@an-a01n01 ~]# drbdadm status
an-test-deploy1 role:Primary
  disk:UpToDate
  an-a01n02 connection:Connecting

[root@an-a01n02 ~]# drbdadm status
an-test-deploy1 role:Secondary
  disk:Diskless
  an-a01n01 connection:StandAlone

**Comment by fabbione** [comment]
This appears to be a race condition.

drbd resource is configured to use:
device    /dev/drbd_an-test-deploy1_0 minor 0;

but that device doesn´t exist yet when drbd is started and it causes the secondary to be in Diskless mode.

**Comment by fabbione** [comment]
```
2022/12/25 09:43:20:[a23c7795]:anvil-provision-server:1105; [ Warning ] - The logical volume: [/dev/anvil-test-vg/an-test-deploy1_0] to use for this server already exists. We will NOT initialize it! If the LV does not have DRBD metadata, the server install will fail. If the LV is a DRBD resource, and it is inconsistent or outdated, provisioning will stall until the peer comes online. If the install fails, please determine why (or remove the existing LV) and try again.
2022/12/25 09:43:28:[scan-drbd]:scan-drbd:470;
A new DRBD resource has been found on this host.
2022/12/25 09:43:28:[scan-drbd]:scan-drbd:998;
A new DRBD resource volume has been found on this host.
- Device Path: . [/dev/drbd_an-test-deploy1_0]
Note: The "minor number" translates to the base '/dev/drbdX' where 'X' is the minor number. The 'device_path' is a convenient symlink to the base 'drbdX' device.
Note: The volume size is always a bit less than the backing LVM logical volume size. Some space is used by the internal DRBD metadata. The size of the metadata is explained here: https://www.linbit.com/drbd-user-guide/drbd-guide-9_0-en/#s-meta-data-size
2022/12/25 09:43:28:[scan-drbd]:scan-drbd:814;
2022/12/25 09:43:29:[a23c7795]:anvil-provision-server:777; The logical volume behind the resource: [an-test-deploy1] existed, and started the resource has the disk state 'diskless'. This is likely because the LV doesn't have DRBD meta-data. We can't (safely) create it. Please either remove the LV backing this resource or create the meta data manually.
```

those logs are interesting. It appears to be some conflict between anvil-provision-server and scan-drbd to enable / configure drbd resources.

**Comment by fabbione** [comment]
Confirmed that the device is missing metadata. Once metadata are recreated, bashing drbdadm with a big hammer, data sync will start somehow.

**Comment by fabbione** [comment]
This is clearly caused by the shutdown/fencing event from DRBD, but it still poses a potential problem as a normal fencing event can happen while deploying a server and leave the disk without metadata.

**Comment by digimer** [comment]
I believe this has been resolved, as I've worked on the components that might cause this, and as of now I can't reproduce it. Please re-open if you are able to reproduce.
