### ISSUE TITLE
[anvil-daemon] high cpu usage on nodes

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#276]
Not clear what´s causing the high load, but CPU are spiking all the time, causing all kind of timeouts with pacemaker and pcs:

Failed Resource Actions:
  * apc_snmp_node1_an-pdu02_monitor_60000 on an-a01n01 'error' (1): call=59, status='complete', last-rc-change='Sun Dec 25 09:31:18 2022', queued=0ms, exec=13200ms
  * virt_node2_gravitar_monitor_60000 on an-a01n01 'error' (1): call=83, status='complete', last-rc-change='Sun Dec 25 09:31:17 2022', queued=0ms, exec=7103ms
  * virt_node1_gravitar_monitor_60000 on an-a01n01 'error' (1): call=28, status='complete', last-rc-change='Sun Dec 25 09:25:40 2022', queued=0ms, exec=7104ms
  * virt_node1_gravitar_start_0 on an-a01n02 'error' (1): call=58, status='complete', last-rc-change='Sun Dec 25 09:32:18 2022', queued=0ms, exec=7092ms
  * apc_snmp_node2_an-pdu02_monitor_60000 on an-a01n02 'error' (1): call=69, status='complete', last-rc-change='Sun Dec 25 09:34:30 2022', queued=0ms, exec=13421ms
  * apc_snmp_node1_an-pdu01_monitor_60000 on an-a01n02 'error' (1): call=65, status='complete', last-rc-change='Sun Dec 25 09:34:29 2022', queued=0ms, exec=12867ms
  * ipmilan_node2_monitor_60000 on an-a01n02 'error' (1): call=47, status='Timed Out', exitreason='Fence agent did not complete within 10s', last-rc-change='Sun Dec 25 09:34:30 2022', queued=0ms, exec=21137ms

**Comment by fabbione** [comment]
2194502 qemu      20   0   21.9g  11.4g  19996 S 204.0  12.1 195:20.55 qemu-system-x86
2215304 qemu      20   0   18.7g   1.9g  20076 S 180.1   2.1  12:27.27 qemu-system-x86
2215843 qemu      20   0   18.3g   1.9g  20220 S 141.7   2.0   8:45.36 qemu-system-x86
2194383 qemu      20   0   21.8g  11.5g  19864 S 139.7  12.2 220:04.52 qemu-system-x86
2194900 qemu      20   0   21.5g  10.3g  19952 S  27.8  11.0 106:49.03 qemu-system-x86

**Comment by fabbione** [comment]
This is slowly becoming an issue the hypervisor is so overloaded that the VMs are pausing and CI fails with random timeouts.

**Comment by fabbione** [comment]
It seems that scancore is causing a CPU spike and that the strikers are more affected by the DB updates. This is just observations right now.

**Comment by fabbione** [comment]
It appears the problem might not be caused by anvil or scancore, but a problem with the hypervisor itself. More investigation to follow.

**Comment by fabbione** [comment]
The problem is unrelated to the hypervisor overheating. I can reproduce similar conditions on phy02.

The CPU spike is more visible when scan-core is running all the plugins, to the point where:

```
Failed Resource Actions:
  * apc_snmp_node1_an-pdu01_monitor_60000 on an-a01n02 'error' (1): call=67, status='complete', last-rc-change='Wed Dec 28 05:42:35 2022', queued=0ms, exec=12950ms
  * ipmilan_node2_monitor_60000 on an-a01n02 'error' (1): call=51, status='complete', last-rc-change='Wed Dec 28 05:40:21 2022', queued=0ms, exec=13273ms
  * apc_snmp_node2_an-pdu02_monitor_60000 on an-a01n02 'error' (1): call=78, status='complete', last-rc-change='Wed Dec 28 05:42:36 2022', queued=0ms, exec=12898ms
  * virt_node1_gravitar_start_0 on an-a01n02 'error' (1): call=82, status='complete', last-rc-change='Wed Dec 28 05:42:39 2022', queued=0ms, exec=6073ms
```

There was a temporary loss of cluster membership as NetworkManager was stuck in D state for a few seconds and network was down.

**Comment by Deezzir** [comment]
I also encountered this issue when I was testing different power loss scenarios and one of the strikers went off for some time. After it was up again the other striker invoked DB sync that overwhelmed the system so much that Scancore missed low battery levels on UPSes. I also saw timeouts with pcs resources. Initially thought that my environment and power loss scenarios were the problem.

**Comment by digimer** [comment]
Resync issues are known and the fix is not easy. Though I agree it is urgent, I need to think of a way to deal with this and it won't be done quickly.

**Comment by digimer** [comment]
I think this was, in part, being caused when both striker dashboards realized they needed to resync, and so both tried to resync at the same time, causing duplicate entries and thus triggering another resync. Commit 5fcbb16 should prevent this behaviour from now on. Re-open is CPU load remains high please.

**Comment by fabbione** [comment]
definitely better than before, still observable spikes on the hypervisor, but no timeouts on normal operations
