### ISSUE TITLE
[fence] fence_ipmilan not correctly configured

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#279]
There are 2 issues with fence_ipmilan configuration.

First is related to how IPMI work. When issuing an IPMI reboot or off command, IPMI simulates a poweroff button. This is intercepted by the OS and executed as orderly shutdown. This is not happening on nodes that are in bad state and therefor fencing will succeed (at pcmk level) but fail in reality to bring the node back online.

https://access.redhat.com/solutions/1578823 explains that /etc/systemd/logind.conf needs to be changed to have:
HandlePowerKey=ignore and systemd-logind restarted.

This part is required regardless on how the second part below is fixed.

Second part is related to pacemaker config. fence_ipmilan is missing: pcmk_off_action=reboot

Now, there are 2 ways to fix this. Either add the option to pacemaker config or fix stonith_admin invocation in fence_pacemaker.

tools/fence_pacemaker:  my $shell_call = $conf->{path}{exe}{stonith_admin}." --fence ".$conf->{cluster}{target_node}." --verbose; RC=\$?; ".$conf->{path}{exe}{crm_error}." \$RC; ".$conf->{path}{exe}{echo}." rc:\$RC";

--fence implies a off action.

stonith_admin also support --reboot. By changing the call to stonith_admin, we can drop completely the bit that requires pacemaker_off_action=reboot.

Both are equivalent.

Personally I would change stonith_admin call and drop the whole bits of pacemaker_off_action,

**Comment by digimer** [comment]
Should be resolved in the next anvil-tools-dev branch PR.

**Comment by fabbione** [comment]
the patch is not correct, reopening

**Comment by digimer** [comment]
Thanks, updating

**Comment by fabbione** [comment]
Verified that logind.conf contains HandlePowerKey=ignore
