### ISSUE TITLE
[simengine] snmpset not working and fence_apc_snmp fails

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#280]
# rpm -qa|grep neo4
python3-neo4j-driver-1.6.1-3.el8.x86_64
neo4j-3.5.35-1.noarch
# rpm -qa|grep simen
simengine-database-3.40-1.el8.noarch
simengine-dashboard-3.40-1.el8.x86_64
simengine-core-3.40-1.el8.x86_64
# rpm -qa|grep libvirt
libvirt-daemon-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-nodedev-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
python3-libvirt-8.0.0-2.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-scsi-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-logical-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-gluster-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-config-nwfilter-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-rbd-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-core-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-iscsi-direct-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-qemu-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-disk-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-nwfilter-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-storage-mpath-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-client-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
fence-virtd-libvirt-1.0.0-5.el8.x86_64
libvirt-daemon-driver-storage-iscsi-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-config-network-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-devel-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-network-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-secret-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-libs-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
libvirt-daemon-driver-interface-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
# rpm -qa|grep qemu
qemu-block-curl-6.1.0-16.el8.x86_64
qemu-system-x86-core-6.1.0-16.el8.x86_64
qemu-char-spice-6.1.0-16.el8.x86_64
qemu-kvm-6.1.0-16.el8.x86_64
qemu-block-iscsi-6.1.0-16.el8.x86_64
qemu-ui-gtk-6.1.0-16.el8.x86_64
qemu-device-display-virtio-gpu-pci-gl-6.1.0-16.el8.x86_64
qemu-audio-spice-6.1.0-16.el8.x86_64
qemu-common-6.1.0-16.el8.x86_64
qemu-audio-oss-6.1.0-16.el8.x86_64
qemu-device-usb-host-6.1.0-16.el8.x86_64
qemu-system-x86-6.1.0-16.el8.x86_64
qemu-img-6.1.0-16.el8.x86_64
qemu-audio-alsa-6.1.0-16.el8.x86_64
qemu-block-rbd-6.1.0-16.el8.x86_64
qemu-device-display-virtio-vga-gl-6.1.0-16.el8.x86_64
libvirt-daemon-driver-qemu-8.0.0-10.module_el8.7.0+1218+f626c2ff.x86_64
qemu-ui-egl-headless-6.1.0-16.el8.x86_64
qemu-audio-sdl-6.1.0-16.el8.x86_64
qemu-device-display-virtio-gpu-6.1.0-16.el8.x86_64
qemu-device-usb-smartcard-6.1.0-16.el8.x86_64
qemu-ui-spice-core-6.1.0-16.el8.x86_64
qemu-audio-pa-6.1.0-16.el8.x86_64
qemu-char-baum-6.1.0-16.el8.x86_64
qemu-device-usb-redirect-6.1.0-16.el8.x86_64
qemu-ui-opengl-6.1.0-16.el8.x86_64
qemu-ui-sdl-6.1.0-16.el8.x86_64
qemu-block-dmg-6.1.0-16.el8.x86_64
qemu-device-display-virtio-gpu-pci-6.1.0-16.el8.x86_64
qemu-ui-curses-6.1.0-16.el8.x86_64
qemu-ui-spice-app-6.1.0-16.el8.x86_64
qemu-device-display-qxl-6.1.0-16.el8.x86_64
ipxe-roms-qemu-20200823-9.git4bd064de.el8.noarch
qemu-device-display-virtio-gpu-gl-6.1.0-16.el8.x86_64
qemu-device-display-virtio-vga-6.1.0-16.el8.x86_64
qemu-block-gluster-6.1.0-16.el8.x86_64
qemu-block-ssh-6.1.0-16.el8.x86_64

simengine is built weekly from simengine git.
qemu is from fedora and rebuilt on top of centos8 (required by simengine for some features not available in centos/rhel).

simegine config:

https://github.com/kronosnet/ci-tools/blob/main/ci-setup-anvil-simengine

from within anvil nodes, fence_apc_snmp appears to be working as all snmpget operations are working perfectly.

On fencing event, when fence_apc_snmp needs to poweroff a VM, snmpset fails.

I wasn´t able to capture the logs from simengine on this round, but i was able to see that the snmpd was failing to set the value for some reasons.

**Comment by fabbione** [comment]
(escalated to simengine upstream)

**Comment by ctyler** [comment]
(I don't see an issue in the simengine upstream repo)

I suspect that either the OID is different from the value we've tested simengine with, or the network connectivity was compromised. 

Can you provide (i) the SNMP OID and value being sent, and/or (ii) a minimal test case/steps to reproduce?
