### ISSUE TITLE
odd error when running anvil-provision-server

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#282]
root@an-a01n01 ~]# anvil-provision-server --ci-test --name an-test-deploy1 --os centos-stream9 --cpu 4 --ram 4G --storage-group "Sto
rage group 1" --storage-size 30G --install-media CentOS-Stream-9-latest-x86_64-dvd1.iso --driver-disc deploy1.iso

2022/12/27 11:15:02:Convert.pm:241; The method: [Convert->bytes_to_human_readable()] was passed the parameter: [hostnmae] with the value: [4G], which is invalid.
2022/12/27 11:15:02:Convert.pm:241; The method: [Convert->bytes_to_human_readable()] was passed the parameter: [hostnmae] with the value: [30G], which is invalid.

**Comment by Deezzir** [comment]
Is the error reproducible?

**Comment by fabbione** [comment]
I have seen it each time.

**Comment by digimer** [comment]
I'm working on the fix now

**Comment by digimer** [comment]
Should be resolved in the next anvil-tools-dev PR

**Comment by fabbione** [comment]
Verified with latest main
