### ISSUE TITLE
[deploy] db init race issues are back on c8s

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#283]
14:34:11 TASK [start anvil deployment and configuration] ********************************
14:34:13 fatal: [an-striker01]: FAILED! => {"changed": true, "cmd": "striker-auto-initialize-all --config /root/anvil_striker_auto.cfg\n", "delta": "0:00:01.251007", "end": "2022-12-27 13:34:13.818161", "msg": "non-zero return code", "rc": 1, "start": "2022-12-27 13:34:12.567154", "stderr": "", "stderr_lines": [], "stdout": "None of the databases are accessible, unable to proceed. Please be sure that 'anvil-daemon' is enabled and running on the database machine(s).", "stdout_lines": ["None of the databases are accessible, unable to proceed. Please be sure that 'anvil-daemon' is enabled and running on the database machine(s)."]}
14:34:13 fatal: [an-striker02]: FAILED! => {"changed": true, "cmd": "striker-auto-initialize-all --config /root/anvil_striker_auto.cfg\n", "delta": "0:00:01.277463", "end": "2022-12-27 13:34:13.849797", "msg": "non-zero return code", "rc": 1, "start": "2022-12-27 13:34:12.572334", "stderr": "", "stderr_lines": [], "stdout": "None of the databases are accessible, unable to proceed. Please be sure that 'anvil-daemon' is enabled and running on the database machine(s).", "stdout_lines": ["None of the databases are accessible, unable to proceed. Please be sure that 'anvil-daemon' is enabled and running on the database machine(s)."]}
14:34:13

**Comment by digimer** [comment]
Might be fixed in #6ca0e0d

**Comment by digimer** [comment]
Tests appear good. Closing for now, can re-open if the issue reappears.

**Comment by fabbione** [comment]
This one seems to be done and gone now. We will continue monitoring CI for related failures.
