### ISSUE TITLE
[provision] server provision does not always work with DRBD fixes (see pr#281)

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#284]
Just making sure the problem is tracked

**Comment by fabbione** [comment]
I added a random sleep 10; at the very end of startup_resource and it seems to solve the issue.

I think startup_resource should check that the disk created by drbd is available in /dev/drbd.. before firing up virt-install call.

**Comment by digimer** [comment]
That should be an easy fix, I'll do that as soon as I'm back to work. Thanks

**Comment by digimer** [comment]
Should be resolved.

**Comment by fabbione** [comment]
verified with latest main
