### ISSUE TITLE
Error after the latest update

### ISSUE THREAD

**Issue by Deezzir** [ClusterLabs/anvil#291]
Version:
anvil-core-2.90-1.1840.d02c.el8.noarch
anvil-striker-2.90-1.1840.d02c.el8.noarch

```
[root@an-striker01 ~]# scancore
scancore has started.
DBD::Pg::st execute failed: ERROR:  relation "dr_links" does not exist
LINE 9:     dr_links 
            ^ at /usr/share/perl5/Anvil/Tools/Database.pm line 16136.
DBD::Pg::st execute failed: ERROR:  relation "dr_links" does not exist
LINE 9:     dr_links 
            ^ at /usr/share/perl5/Anvil/Tools/Database.pm line 16136.
```

NOTE: need to add `anvil-version-change` to the RPM %post

**Comment by digimer** [comment]
I need to add a call to anvil-striker's %post to call anvil-version-changes in the RPM spec file.

**Comment by fabbione** [comment]
The whole update business is rather complex and for who is using older versions of anvil, they will first need to upgrade manually to the latest version, by stopping anvil and scancore on all nodes, yum update, update the db and then start anvil and scancore.

In the most recent versions of anvil, a new tool called striker-update-cluster is available to automate the whole update (including reboots, VM migrations and stuff).
