### ISSUE TITLE
file sync must use iorenice

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#292]
when running rsync for huge files, the rsync IO is so high that the pacemaker cluster explodes in various timeout.

This is most likely an issue that we will see only in CI but it can potentially affect slow I/O real machines as well.

**Comment by fabbione** [comment]
another option is not to run N rsync in parallel but serialize them.

**Comment by digimer** [comment]
Agreed, these should be serial, not parallel copies. This is going to be a non-trivial change though. I will reassign this to 'high' and make it the next task, baring any new 'urgent' bugs. Please re-assign this as 'urgent' if it's a blocker for CI.

**Comment by digimer** [comment]
This should be fixed in PR#308.

**Comment by fabbione** [comment]
how was this fixed and what behavior should I expect now?

**Comment by digimer** [comment]
When it sees a new file, it serially rsync's the file to strikers first, then nodes, and then DR hosts. If a given target is not available at the time, a job is created for that host to pull it when it's next online.

**Comment by fabbione** [comment]
Serial seems to be working reliably and much faster than parallel on CI nodes
