### ISSUE TITLE
anvil-daemon odd error message during file sync

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#293]
in CI we do pass around a 8.5GB iso image to deploy servers around.

during the transfer we see:

2023/01/19 09:29:32:anvil-daemon:288; The program: [anvil-daemon] is using: [8.80 GiB] (9,448,928,051 Bytes). This is probably caused by a memory leak, so we will now exit so that systemctl can restart us. If this is happening repeatedly, please contact support.

It appears as if anvil-daemon is loading the whole file to calculate the md5sum. This shouldn´t be necessary at all and it triggers an unnecessary (scary?) restart of anvil-daemon

**Comment by digimer** [comment]
Hrm, it's supposed to check if a file transfer is underway and suppress this if not. So it is a bug and needs to be resolved. However, given that it doesn't seem to be breaking anything, I'll reset this to "high". I'll try to fix this next week. Please re-label as 'urgent' if it is breaking something.

**Comment by fabbione** [comment]
It did leave anvil in an odd situation, where cluster was not running (due to high I/O), anvil-daemon restarted and cluster was not recovered.

**Comment by digimer** [comment]
Noted. This will be the first priority after the next enterprise repo update. Resetting to "urgent" to make sure it's top of the ToDo list.

**Comment by fabbione** [comment]
This appears to be fixed after moving to serial rsync. Will keep an eye but close it for now.
