### ISSUE TITLE
ScanCore Agents running too long 

### ISSUE THREAD

**Issue by Deezzir** [ClusterLabs/anvil#303]
I am running a scenario where one of the power outlets goes down, and the UPS connected to it starts to drain. At some point, almost every Scancore instance on the machines hangs. Saw “cluster” and “ipmi” agents running for almost 700secs. I deducted that it’s related to PCS resource time-outs. Possibly, there is a bug with some of the ScanCore agents. 

I have a configuration where the UPS drains for 900 secs, the ScanCore on the nodes and one of the strikers hangs for almost the whole draining period. I will collect more logs regarding the issue.

**Comment by Deezzir** [comment]
Found the issue - the problem was with the IPMI simulation from Simengine; there was a password set on the IPMI, and ScanCore could not access it. It might explain why `scan-cluster` and `scan-ipmi` run for so long(around 700 seconds. Not sure if the long timeout itself should be addressed, but leave it here for now

**Comment by fabbione** [comment]
We never experienced this problem in CI where anvil sets the passwords within SimEngine and access is working fine.

I suspect that there was a misconfiguration in your setup where SimEngine was configured with different passwords from anvil deployment.
