### ISSUE TITLE
all tools that manage server / resource should support --ci-test and command line input (non-interactive)

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#321]
Similar to what was done with anvil-provision-server, we need to be able to manipulate everything automatically from command line.

The very first tool that needs to be ported (urgent) is anvil-delete-server.

**Comment by digimer** [comment]
Will do!

**Comment by fabbione** [comment]
anvil-delete-server --server <name_or_uuid> --force appears to work as expected.

**Comment by fabbione** [comment]
leaving open for now as other tools might need command line options.

**Comment by fabbione** [comment]
a tool that is a good candidate to have machine parsable output is anvil-report-usage. It will allow dynamic creating of tests and verification of resource leaks.

**Comment by digimer** [comment]
Now supports --machine, which produces output like:

```
<?xml version="1.0" ?>
<resources>
	<servers>
		<server name="srv01" uuid="3015b89b-5d12-45c5-85d7-bfa84b138550">
			<anvil name="vm-anvil-01" uuid="b0f1a959-c333-4159-8703-df6c1dff6c70" />
			<cpu cores="2" threads="1" sockets="1" model="Cooperlake" fallback="forbid" match="exact" vendor="Intel" mode="custom" />
			<ram used_bytes="2147483648" used_hr="2.00 GiB" />
			<storage resource="srv01">
				<volume number="0" size-bytes="53687091200" size-hr="50.00 GiB" storage-group="Storage group 1">
					<subnode name="vm-a01n01" host-uuid="8b6a090b-67f0-4f2c-827d-f5685c6f034d" path="/dev/drbd44" res-path="/dev/drbd/by-res/srv01/0" minor="44" meta-data="internal" lv="/dev/cs_vm-a01n01/srv01_0" />
					<subnode name="vm-a01n02" host-uuid="c7979243-fca2-47e8-a785-36c80c078c94" path="/dev/drbd44" res-path="/dev/drbd/by-res/srv01/0" minor="44" meta-data="internal" lv="/dev/cs_vm-a01n02/srv01_0" />
				</volume>
			</storage>
			<network bridge="ifn1_bridge1">
				<mac alias="" address="52:54:00:b0:ad:c8" model="virtio" ip="192.168.6.56" />
			</network>
		</server>
	</server>
		<server name="srv02" uuid="223fe21f-88f9-48c3-a40d-353e7e750ff4">
			<anvil name="vm-anvil-01" uuid="b0f1a959-c333-4159-8703-df6c1dff6c70" />
			<cpu cores="2" threads="1" sockets="1" model="" fallback="" match="" vendor="" mode="host-model" />
			<ram used_bytes="2147483648" used_hr="2.00 GiB" />
			<storage resource="srv02">
				<volume number="0" size-bytes="21474836480" size-hr="20.00 GiB" storage-group="Storage group 1">
					<subnode name="vm-a01n01" host-uuid="8b6a090b-67f0-4f2c-827d-f5685c6f034d" path="/dev/drbd45" res-path="/dev/drbd/by-res/srv02/0" minor="45" meta-data="internal" lv="/dev/cs_vm-a01n01/srv02_0" />
					<subnode name="vm-a01n02" host-uuid="c7979243-fca2-47e8-a785-36c80c078c94" path="/dev/drbd45" res-path="/dev/drbd/by-res/srv02/0" minor="45" meta-data="internal" lv="/dev/cs_vm-a01n02/srv02_0" />
				</volume>
			</storage>
			<network bridge="ifn1_bridge1">
				<mac alias="" address="52:54:00:78:32:77" model="virtio" ip="192.168.6.72" />
			</network>
		</server>
	</server>
	<nodes>
		<node name="vm-anvil-01" uuid="b0f1a959-c333-4159-8703-df6c1dff6c70" description="Test anvil! on the laptop">
			<cpu cores="4" threads="4" />
			<ram hardware="34359738368" hardware-hr="24.00 GiB" used="4294967296" used-hr="4.00 GiB" available="25769803776" available-hr="24.00 GiB" />
			<bridges available="bcn1_bridge1, ifn1_bridge1" />
			<storage-group name="Storage group 1" uuid="f278efd7-2ae6-42d1-ab90-fd65118b3e26" used-bytes="158779572224" used-hr="147.88 GiB" free-bytes="107948802048" free-hr="100.54 GiB" />
		</node>
	</nodes>
</resources>

```

**Comment by digimer** [comment]
This should be resolved in PR #376 (commit #d07933a). Please close this when you're happy with the output.

**Comment by digimer** [comment]
Hold, XML is invalid, will correct in the next commit.

**Comment by digimer** [comment]
XML now appears valid in commit 9b90647.

**Comment by fabbione** [comment]
[root@an-a01n01 ~]# anvil-report-usage --machine | xmllint -
-:20: parser error : attributes construct error
de name="an-anvil-01" uuid="65559354-9b57-46fb-8880-169ca92804b2" description=""
                                                                               ^
-:20: parser error : Couldn't find end of Start Tag node line 20
de name="an-anvil-01" uuid="65559354-9b57-46fb-8880-169ca92804b2" description=""
                                                                               ^
-:25: parser error : Opening and ending tag mismatch: nodes line 19 and node
                </node>
                       ^
-:26: parser error : Opening and ending tag mismatch: resources line 2 and nodes
        </nodes>
                ^
-:27: parser error : Extra content at the end of the document
</resources>
^

**Comment by fabbione** [comment]
<node name="an-anvil-01" uuid="65559354-9b57-46fb-8880-169ca92804b2" description=""Test Anvil! running on gravitar"">

**Comment by digimer** [comment]
Ah, double-quotes, woops.

**Comment by fabbione** [comment]
Confirmed to be working in latest PR376
