### ISSUE TITLE
Spelling error in `anvil-boot-server` help text

### ISSUE THREAD

**Issue by maholloway** [ClusterLabs/anvil#359]
After the **Commands** seciton of the `anvil-boot-server` help text, a sentence begins:

"Be away that when this is used..."

One suspects this is intended to read as:

"Be aware that when this is used..."

**This line is number 43 in /usr/share/man/man8/anvil-boot-server.8**

Tiny whoopsie, to be sure, however it may be of importance at some point in the future, and I thought it worth documenting.

**Comment by digimer** [comment]
Thanks, fixed! It will be fixed in the next PR from anvil-tools-dev.
