### ISSUE TITLE
[upgrade] process does not complete

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#367]
[root@an-striker01 ~]# striker-update-cluster -vv --log-secure --clear-cache --reboot --yes
- Verifying access to: [an-a01n01]... Connected on: [10.201.10.1] via: [bcn1]
- Verifying access to: [an-a01n02]... Connected on: [10.201.10.2] via: [bcn1]
- Verifying access to: [an-striker01]... Connected on: [10.201.4.1] via: [bcn1]
- Verifying access to: [an-striker02]... Connected on: [10.201.4.2] via: [bcn1]
Success!
[ Note ] - Proceeding without confirmation, '-y' or '--yes' used.
Disabling Anvil! daemons on all hosts...
- Disabling dameons on: [an-a01n01]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-a01n02]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-striker01]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-striker02]... anvil-daemon stopped... scancore stopped... Done!
Starting the update of the Striker dashboard: [an-striker01].
- Beginning OS update of: [an-striker01]
- Cache cleared.
- Calling update now.
- NOTE: This can seem like it's hung! You can watch the progress using 'journalctl -f' on another terminal to
-       watch the progress via the system logs. You can also check wiht 'ps aux | grep dnf'.
- The kernel has not been updated.
- Reboot not needed, kernel appears to be up to date.
- Running 'anvil-version-changes' now.
Starting the update of the Striker dashboard: [an-striker02].
- Beginning OS update of: [an-striker02]
- Calling update now.
- NOTE: This can seem like it's hung! You can watch the progress using 'journalctl -f' on another terminal to
-       watch the progress via the system logs. You can also check wiht 'ps aux | grep dnf'.
- Beginning OS update of: [an-striker02]
- [ Note ] - Job registered with UUID: [bea3adc2-b2a4-4791-8d61-650555c665fc], waiting for it to complete.
- Making sure anvil-daemon is running...  running.
 - Done! The host: [an-striker02] has been updated
- Reboot not needed, kernel appears to be up to date.
- Running 'anvil-version-changes' now.
Enabling Anvil! daemons on all hosts...
- Enabling dameons on: [an-a01n01]... anvil-daemon started... scancore started... Done!
- Enabling dameons on: [an-a01n02]... anvil-daemon started... scancore started... Done!
- Enabling dameons on: [an-striker01]... anvil-daemon started... scancore started... Done!
- Enabling dameons on: [an-striker02]... anvil-daemon started... scancore started... Done!
Preparing to update the Anvil! node: [an-anvil-01]. Verifying subnode access:
- Verifying access to subnode: [an-a01n02]
- Access found uver the: [bcn1] networking using the IP: [10.201.10.2]
- Access found uver the: [ifn1] networking using the IP: [192.168.122.5]
- Verifying access to subnode: [an-a01n01]
- Access found uver the: [bcn1] networking using the IP: [10.201.10.1]
- Access found uver the: [ifn1] networking using the IP: [192.168.122.4]
Preparing to update: [an-a01n02]. Withdrawing the subnode from the Anvil! node.
- [ Note ] - If the node has servers that need to be migrated off, or if the node is SyncSource for storage,
- [ Note ] - this could take some time to complete.
- [ Note ] - Job registered with UUID: [263b5338-8f0f-4a27-a655-0c4475627fa0], waiting for it to complete.
- Making sure anvil-daemon is running...  running.
- The subnode is out of the node cluster. Proceeding.
- Beginning OS update of: [an-a01n02]
- [ Note ] - Job registered with UUID: [77ff6ec7-aa01-4668-ba60-20c7e9440530], waiting for it to complete.
 - Done! The host: [an-a01n02] has been updated
- Update completed successfully! Checking if a reboot is needed.
- Reboot not needed, kernel appears to be up to date.
- Waiting for the subnode to rejoin the node.
- Calling 'anvil-safe-start' to rejoin the subnode to the node.
- Unable to parse the node's cluster information base, will try again soon.
- Unable to parse the node's cluster information base, will try again soon.
- Unable to parse the node's cluster information base, will try again soon.
 - Unable to parse the node's cluster information base, will try again soon.
- Unable to parse the node's cluster information base, will try again soon.
^C

Process with PID: [291270] exiting on SIGINT.

**Comment by digimer** [comment]
This should be resolved in PR #376 .

**Comment by fabbione** [comment]
confirmed the update completed.
