### ISSUE TITLE
[upgrade] upgrade sequence is dangerous and incorrect

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#368]
snip of the upgrade output:

Disabling Anvil! daemons on all hosts...
- Disabling dameons on: [an-a01n01]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-a01n02]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-striker01]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-striker02]... anvil-daemon stopped... scancore stopped... Done!

- Beginning OS update of: [an-striker01] <- OK

- Running 'anvil-version-changes' now. <- DANGEROUS (see below)

- Beginning OS update of: [an-striker02] <- OK

- Running 'anvil-version-changes' now. <- MAYBE OK? what about DB sync process? can they clash?

Enabling Anvil! daemons on all hosts...
- Enabling dameons on: [an-a01n01]... anvil-daemon started... scancore started... Done! <- DANGEROUS
- Enabling dameons on: [an-a01n02]... anvil-daemon started... scancore started... Done! <- DANGEROUS
- Enabling dameons on: [an-striker01]... anvil-daemon started... scancore started... Done!
- Enabling dameons on: [an-striker02]... anvil-daemon started... scancore started... Done!

The anvil-daemons on the nodes are not updated to deal with any of the DB changes yet. They should not be started before the OS upgrade as DB might have changed in some incompatible ways. This can cause DB corruption and anvil-daemon to crash on the nodes if data made available by DB are different.
Probably similar apply to the DR node.

**Comment by digimer** [comment]
I need anvil-daemon to run for the jobs to kick off. When I tried updating directly, I'd get ssh timeouts which would break the update process.

**Comment by fabbione** [comment]
This appears to be fixed in PR376.
