### ISSUE TITLE
Need to add kmod-megaraid_sas

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#372]
Red Hat has deprecated kmod-megaraid_sas, which a lot of our clients use. It's available in elrepo, so we'll need to add it to our own repos.

**Comment by nummysquee** [comment]
Attempting to use drivers held in elrepo-release.

**Comment by fabbione** [comment]
@nummysquee does the driver actually work?

**Comment by nummysquee** [comment]
It looks like the initramfs was never generated, trying to duplicate the
original issue but having no luck

**Comment by digimer** [comment]
Spoke, decided we're not adding the driver for liability reasons, effected users will have to stay on old kernel until replacement hardware can be arranged.
