### ISSUE TITLE
man/Makefile.am man variable update

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#375]
There are two lists, dist_man5_MANS and dist_man8_MANS. Under dist_man8_MANS, 'anvil-manage-keys.1' is listed. Should this be moved to a new dist_man1_MANS?

**Comment by fabbione** [comment]
Yes it should be moved.

**Comment by fabbione** [comment]
Nope, just need to remove the duplicate from the man8 section.

**Comment by digimer** [comment]
Should be resolved in f998a44

**Comment by fabbione** [comment]
the fix appears to be correct.
