### ISSUE TITLE
[upgrade] anvil-daemons and scancore are not disabled during update

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#380]
Disabling Anvil! daemons on all hosts...
- Disabling dameons on: [an-a01n01]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-a01n02]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-striker01]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-striker02]... anvil-daemon stopped... scancore stopped... Done!

something is re-enabling them again and they are running during the update.

**Comment by digimer** [comment]
They're enabled in the rpm spec file so they start when updated.

**Comment by fabbione** [comment]
ok, I think that should be safe enough.

**Comment by digimer** [comment]
For later reference; anvil-update-system enables/starts anvil-daemon and scancore if it was run with --no-db after the OS update is done.
