### ISSUE TITLE
[upgrade] tool brings node down for no reason and does not recover

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#381]
Preparing to update: [an-a01n02]. Withdrawing the subnode from the Anvil! node.
- [ Note ] - If the node has servers that need to be migrated off, or if the node is SyncSource for storage,
- [ Note ] - this could take some time to complete.
- Waiting for all DRBD resource (and the servers using them) to stop before proceeding.
- Registering a job to update the subnode, which we can track to confirm when the update is done.
- [ Note ] - Job registered with UUID: [f49b132a-88fa-4e12-8368-8fb4847d758c], waiting for it to complete.
- Calling the no-database update of: [an-a01n02]
 [ Note ] - [05:32:46] - The job progress is: [0], continuing to wait.
[ Note ] - [05:32:46] - It is expected for the job to stay at '0' for a while.

--- node is rebooted and rejoins anvil / cluster / drbd correctly ---

something is happening here... cluster on the node is disabled, drbd is not running

[ Note ] - [05:36:01] - It is expected for the job to stay at '0' for a while.
  [ Note ] - [05:37:06] - The job progress is: [3], continuing to wait.
[ Note ] - [05:38:11] - The job progress is: [3], continuing to wait.
   - Done! The subnode: [an-a01n02] has been updated
- Update completed successfully! Checking if a reboot is needed.
- Rebooted! Will wait for it to come back up.
- The target has been rebooted. We'll wait for the target to come back online.
- Rebooted! Subnode is back up.
- Waiting for the subnode to rejoin the node.
 - Unable to parse the node's cluster information base, will try again soon.
 - Unable to parse the node's cluster information base, will try again soon.
- Unable to parse the node's cluster information base, will try again soon.

waited 5 minutes, nothing is happening....

**Comment by digimer** [comment]
I'll try to reproduce

**Comment by digimer** [comment]
I believe I found the problem and fixed it in PR #376.

**Comment by fabbione** [comment]
this seems to be fixed in #376
