### ISSUE TITLE
[upgrade] fix timeout bits

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#383]
2 bits here:
- make timeout in minutes, hardly any system updates in seconds
- clarify in the man page if the timeout is global for all configured systems or per-node

**Comment by digimer** [comment]
Done. Supports '--timeout X' for seconds, '--timeout Xm' for minutes and '--timeout Xh' for hours. In commit ed480cf

**Comment by digimer** [comment]
Also, on the '--timeout' being global; The timeout is for all places in striker-update-cluster where it waits for anything to happen. I can amend the man page to clarify, if this is what you were asking for clarity on. If not, please let me know

**Comment by fabbione** [comment]
Yeah it´s not clear if  timeout is global, or per node, or per action.
