### ISSUE TITLE
[update] prefix striker-update-cluster with timestamps

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#384]
it would be good for debugging purposes to have each operation printed by the tool to be timestamped consistently with logs. In case of issues it will be easier to correlate failures with events.

**Comment by digimer** [comment]
You mean all the text printed to STDOUT should have timestamps?

**Comment by fabbione** [comment]
yes

**Comment by digimer** [comment]
OK, I can add that, but that'll take a bit of time. Currently it's direct printing, and I need to move it to the translation system. I can add timestamps to the output then.

**Comment by digimer** [comment]
This should be done, please close if you can confirm this is working.

**Comment by fabbione** [comment]
verified, we are not going to add test automation for this.
