### ISSUE TITLE
[update] timeout does not work as documented

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#385]
striker-update-cluster -vv --log-secure --clear-cache --reboot --yes --timeout 1800

according to the man page, that´s in second.

waited about 3 hours and it´s still waiting in:
- Unable to parse the node's cluster information base, will try again soon.
- Unable to parse the node's cluster information base, will try again soon.

**Comment by fabbione** [comment]
testing the "absurd":

# striker-update-cluster -vv --log-secure --clear-cache --reboot --yes --timeout 1m
- Verifying access to: [an-a01n01]... Connected on: [10.201.10.1] via: [bcn1]
- Verifying access to: [an-a01n02]... Connected on: [10.201.10.2] via: [bcn1]
- Verifying access to: [an-striker01]... Connected on: [10.201.4.1] via: [bcn1]
- Verifying access to: [an-striker02]... Connected on: [10.201.4.2] via: [bcn1]
Success!
[ Note ] - Proceeding without confirmation, '-y' or '--yes' used.
Disabling Anvil! daemons on all hosts...
- Disabling dameons on: [an-a01n01]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-a01n02]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-striker01]... anvil-daemon stopped... scancore stopped... Done!
- Disabling dameons on: [an-striker02]... anvil-daemon stopped... scancore stopped... Done!
Starting the update of the Striker dashboard: [an-striker01].
- Beginning OS update of: [an-striker01]
- Cache cleared.
- Calling update now.
- NOTE: This can seem like it's hung! You can watch the progress using 'journalctl -f' on another terminal to
-       watch the progress via the system logs. You can also check wiht 'ps aux | grep dnf'.
- The kernel has not been updated.
- Reboot not needed, kernel appears to be up to date.
- Running 'anvil-version-changes' now.
Starting the update of the Striker dashboard: [an-striker02].
- Beginning OS update of: [an-striker02]
- Calling update now.
- NOTE: This can seem like it's hung! You can watch the progress using 'journalctl -f' on another terminal to
-       watch the progress via the system logs. You can also check wiht 'ps aux | grep dnf'.
- Beginning OS update of: [an-striker02]
- Registering a job to update the system, which we can track to confirm when the update is done.
- [ Note ] - Job registered with UUID: [24129408-2e8f-415e-a2ce-779dc6111e58], waiting for it to complete.
- Calling the no-database update of: [an-striker02]
  - Done! The host: [an-striker02] has been updated
- Rebooted! Will wait for it to come back up.
- The target has been rebooted. We'll wait for the target to come back online.

    - [15:21:19] - We're still waiting for the subnode: [an-striker02] to reboot.
- Waiting for another: [-4], will check again shortly.
[ Error ] - Timed out while waiting for the subnode: [an-striker02] to reboot. Aborting the update.

timer expired much earlier than 15:21:19.  I fired the job around 15:18...

this is not critical and no blocker. At least a timeout works somehow.

**Comment by digimer** [comment]
If a timeout is specified, use it to set the timeout for all loops

**Comment by fabbione** [comment]
Blocked by #623

**Comment by digimer** [comment]
Should now be resolved. Will re-open if further failures occur.
