### ISSUE TITLE
ocf:alteeve:server typo

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#390]
# pcs resource describe ocf:alteeve:server
ocf:alteeve:server - Anvil! m3 server resource agent

This resource agent manages KVM+qemu virtual servers on an Anvil! m3 Intelligent Availability(tm) system.  It manages underlying components like DRBD 9 storage resources, brodge connections and so forth.

"brodge" :)

**Comment by digimer** [comment]
Thanks, fixed in my local branch, will be in the next PR.

**Comment by digimer** [comment]
Fixed in bf2622a

**Comment by fabbione** [comment]
will not add automation on a typo.
