### ISSUE TITLE
Wrong default IP in Striker config

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#399]
The default BCN 1 IP address is '10.200.1.1' and the default IFN 1 IP address is '10.201.1.1'. 

The BCN 1 should default to 10.201.1.1 (if the sequence is '1', 10.201.1.2 if the sequence is '2', etc). The IFN should be blank, as we can't predict what it will be.

See:

https://wiki.alteeve.com/images/e/ec/An-striker01-rhel8-m3-initial-setup-06.png

**Comment by digimer** [comment]
Yan, after fixing, reassign this issue to me.

Future me: fter fixing, update relevant screenshots:

https://wiki.alteeve.com/index.php?title=Build_an_M3_Anvil!_Cluster#Configuring_the_Striker_Dashboards

**Comment by ylei-tsubame** [comment]
This issue can be closed after #402 is merged.

The enhancement part of this issue is moved to #413.
