### ISSUE TITLE
Adding a peer Striker when the local login is saved pre-populates the peer form fields

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#404]
When a user saves the Striker login credentials, and then they try to peer a striker, the saved username (admin) is used to populate the 'IP address' form.

![Screenshot from 2023-08-05 14-32-33](https://github.com/ClusterLabs/anvil/assets/189162/41ee2468-148b-46e1-af53-2e685b548b06)

Separately, the peer user needs to always be 'root', so I think we can drop field and just ask for the IP and password.

**Comment by ylei-tsubame** [comment]
Different browsers have different ways of guessing which fields to auto-fill with the saved values. For example, [Google's standards](https://stackoverflow.com/a/41965106) doesn't work with firefox; haven't found firefox's standards yet.
