### ISSUE TITLE
Saving a peer striker job doesn't clear the screen

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#410]
After saving the job, there's no way for the user to close the "Add a peer" menu.

![Screenshot_vm-striker01_2023-08-08_17:00:12](https://github.com/ClusterLabs/anvil/assets/189162/a29a5899-4707-4b7e-9afa-568bc082bd39)

This should either auto-close after five seconds, or, better, provide a button for the user to click to go back to the main page.

**Comment by ylei-tsubame** [comment]
Close the dialog after the success message, maybe timeout 3-5 seconds. Note this in the message.
