### ISSUE TITLE
Striker Peers don't show up in the UI

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#411]
As seen below, a peer is configured (and confirmed in the hosts table), but the menu doesn't show in the list.

![Screenshot_vm-striker01_2023-08-08_23:28:23](https://github.com/ClusterLabs/anvil/assets/189162/4df2d55f-6c3d-49b8-90bc-1da353eab05e)

**Comment by ylei-tsubame** [comment]
This issue cannot be replicated after the striker (that was having this issue rebooted). Pushing this to pre-GA until further notice.

**Comment by ylei-tsubame** [comment]
Likely the same as #519
