### ISSUE TITLE
When initializating a host, there's no way to go back if the user connected to the wrong host.

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#414]
In the example below, I connected to 'an-a01n01.alteeve.com'. If this had been wrong, I wouldn't be able to go back to enter a new IP (Test Access).

![Screenshot_vm-striker01_2023-08-09_19:54:08](https://github.com/ClusterLabs/anvil/assets/189162/a282223c-eaca-4ee0-971a-b1327e1416a0)

**Comment by digimer** [comment]
When the node or DR host has been initialized, it shows that the job has been saved for a few second, and then it fades out. If the user misses this, they won't realize they've already requested the initialization. 

Leave the "job saved" message up, and add the 'X' icon to return the user back to the start. And/or, provide an option to "initialize another host" button after saved, as often a user will be initializating multiple hosts.

At the page with the radio buttons, we should show a list of nodes and DR hosts that have been initialized but not yet assigned to an Anvil! node or DR hosts not yet linked to any Anvil! nodes. This would let the use to see which have already been initialized, and which still need to be initialized.

**Comment by ylei-tsubame** [comment]
You should be able to just change the IP address or password and the reset of the form should reset.
