### ISSUE TITLE
data grab script is borked

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#534]
Grabbing logs and data from the remote system: [an-a01n02].
- Testing access...
- Found access over the network: [bcn1] using the target IP: [10.201.10.2]
- Found access over the network: [ifn1] using the target IP: [192.168.122.5]
- Writing out system logs from the previous boot... Done! Copying to here... Done.
- Grabbing system logs from this boot... Done! Copying to here... Failed!
- For some reason, this file was not collected.
- Grabbing cloud-init logs... Failed!
- For some reason, these files were not collected.
- Grabbing hosts file... Failed!
- For some reason, this file was not collected.
- Grabbing Anvil! log... Failed!
- For some reason, this file was not collected.
- Collecting the cluster information base (CIB)... Done! Copying to here... Done.
- Collecting server definitions... Done!
- Collecting replicated storage config... Done!
Data collection complete, creating the tarball now... Done!

**Comment by digimer** [comment]
This is mostly fixed. The CIB is not downloaded, but the main issue has been resolved.

**Comment by digimer** [comment]
The pcs wrapper returned 127, which is usually a timeout. So I'm testing switching to a direct pcs call to dump the CIB, given the test is over at that point anyway. This is the last issue with log collection still, I think.

**Comment by fabbione** [comment]
Pushing back to devel:

- Collecting the cluster information base (CIB)... Done! Copying to here... Failed!
- For some reason, this file was not collected.

Note that the CIB copy is done, but the copy fails. It´s not pcs wrapper here.
