### ISSUE TITLE
Striker initialization form won't allow submitting even when all fields are complete

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#562]
Specifically, I setup the network first (mapped NICs, set IPs, gateway, etc), then I went up and filled the top of the form out (sequence, name, password, etc) and the "Initialize" button stayed grayed out. I had to re-edit the DNS field and then it finally enabled the button. Once all fields are good, the button should become available.

**Comment by ylei-tsubame** [comment]
Couldn't reproduce on a new striker, but can be reproduced on reconfigure.

Reconfigure fills all known fields except for the password fields. The submit button doesn't enable after filling the password fields; the user needs to change at least one other field, i.e. DNS, to get the submit button to enable.

However, this issue should be solved once we switch the striker config forms to use the formik module.
