### ISSUE TITLE
[update] perl traceback during update

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#649]
https://ci.kronosnet.org/job/anvil/job/anvil-build-functional-testing/10831/anvil-build-all-voting-functional-testing=anvil-bm/console

fatal: [an-striker01]: FAILED! => {"changed": true, "cmd": "striker-update-cluster -vv --log-secure --clear-cache --timeout 60m --reboot --yes\n", "delta": "0:01:15.996163", "end": "2024-04-21 15:31:32.091395", "msg": "non-zero return code", "rc": 255, "start": "2024-04-21 15:30:16.095232", "stderr": "Can't use string (\"!!error!!\") as an ARRAY ref while \"strict refs\" in use at /usr/share/perl5/Anvil/Tools/Get.pm line 1458.", "stderr_lines": ["Can't use string (\"!!error!!\") as an ARRAY ref while \"strict refs\" in use at /usr/share/perl5/Anvil/Tools/Get.pm line 1458."], "stdout": "- Verifying access to: [an-a01n01]... Connected on: [10.201.10.1] via: [bcn1]\n- Verifying access to: [an-a01n02]... Connected on: [10.201.10.2] via: [bcn1]\n- Verifying access to: [an-striker01]... Connected on: [10.201.4.1] via: [bcn1]\n- Verifying access to: [an-striker02]... Connected on: [10.201.4.2] via: [bcn1]\nSuccess!\n[ Note ] - Proceeding without confirmation, '-y' or '--yes' used.\nDisabling Anvil! daemons on all hosts...\n- Disabling dameons on: [an-a01n01]... anvil-daemon stopped... scancore stopped... Done!\n- Disabling dameons on: [an-a01n02]... anvil-daemon stopped... scancore stopped... Done!\n- Disabling dameons on: [an-striker01]... anvil-daemon stopped... scancore stopped... Done!\n- Disabling dameons on: [an-striker02]... anvil-daemon stopped... scancore stopped... Done!\nStarting the update of the Striker dashboard: [an-striker01].\n- Beginning OS update of: [an-striker01]\n- Cache cleared.\n- Calling update now.\n- NOTE: This can seem like it's hung! You can watch the progress using 'journalctl -f' on another terminal to\n-       watch the progress via the system logs. You can also check wiht 'ps aux | grep dnf'.\n- The kernel has not been updated.\n- Reboot not needed, kernel appears to be up to date.\n- Running 'anvil-version-changes' now.\nStarting the update of the Striker dashboard: [an-striker02].\n- Beginning OS update of: [an-striker02]\n- Calling update now.\n- NOTE: This can seem like it's hung! You can watch the progress using 'journalctl -f' on another terminal to\n-       watch the progress via the system logs. You can also check wiht 'ps aux | grep dnf'.\n- Beginning OS update of: [an-striker02]\n- Registering a job to update the system, which we can track to confirm when the update is done.\n- [ Note ] - Job registered with UUID: [506c4549-8181-4db5-b451-e58ef690295a], waiting for it to complete.\n- Calling the no-database update of: [an-striker02]\n- Done! The host: [an-striker02] has been updated\n- Rebooted! Will wait for it to come back up.\n- The target has been rebooted. We'll wait for the target to come back online.", "stdout_lines": ["- Verifying access to: [an-a01n01]... Connected on: [10.201.10.1] via: [bcn1]", "- Verifying access to: [an-a01n02]... Connected on: [10.201.10.2] via: [bcn1]", "- Verifying access to: [an-striker01]... Connected on: [10.201.4.1] via: [bcn1]", "- Verifying access to: [an-striker02]... Connected on: [10.201.4.2] via: [bcn1]", "Success!", "[ Note ] - Proceeding without confirmation, '-y' or '--yes' used.", "Disabling Anvil! daemons on all hosts...", "- Disabling dameons on: [an-a01n01]... anvil-daemon stopped... scancore stopped... Done!", "- Disabling dameons on: [an-a01n02]... anvil-daemon stopped... scancore stopped... Done!", "- Disabling dameons on: [an-striker01]... anvil-daemon stopped... scancore stopped... Done!", "- Disabling dameons on: [an-striker02]... anvil-daemon stopped... scancore stopped... Done!", "Starting the update of the Striker dashboard: [an-striker01].", "- Beginning OS update of: [an-striker01]", "- Cache cleared.", "- Calling update now.", "- NOTE: This can seem like it's hung! You can watch the progress using 'journalctl -f' on another terminal to", "-       watch the progress via the system logs. You can also check wiht 'ps aux | grep dnf'.", "- The kernel has not been updated.", "- Reboot not needed, kernel appears to be up to date.", "- Running 'anvil-version-changes' now.", "Starting the update of the Striker dashboard: [an-striker02].", "- Beginning OS update of: [an-striker02]", "- Calling update now.", "- NOTE: This can seem like it's hung! You can watch the progress using 'journalctl -f' on another terminal to", "-       watch the progress via the system logs. You can also check wiht 'ps aux | grep dnf'.", "- Beginning OS update of: [an-striker02]", "- Registering a job to update the system, which we can track to confirm when the update is done.", "- [ Note ] - Job registered with UUID: [506c4549-8181-4db5-b451-e58ef690295a], waiting for it to complete.", "- Calling the no-database update of: [an-striker02]", "- Done! The host: [an-striker02] has been updated", "- Rebooted! Will wait for it to come back up.", "- The target has been rebooted. We'll wait for the target to come back online."]}

**Comment by digimer** [comment]
Should now be resolved. Will re-open if further failures occur.
