### ISSUE TITLE
Make the spec file leave the daemons off if they were off at the time the RPM is updated

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#676]
There's a rpm macros to handles for this.

**Comment by digimer** [comment]
You should be able to find examples in other spec files to show how this is handled, like potentially apache.

**Comment by ylei-tsubame** [comment]
Should follow the Fedora Packaging Guidelines: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd
